# SPDX-License-Identifier: GPL-2.0

EXAMPLE_INFO_SRC := $(EXAMPLE_INFO).c
EXAMPLE_PLAY_SRC := $(EXAMPLE_PLAY).c

EXAMPLE_SRC := $(EXAMPLE_INFO_SRC) $(EXAMPLE_PLAY_SRC)

EXAMPLE_LINK_OBJ +=							\
	lib/ice/ice.o							\
	system/unix/file.o						\
	system/unix/memory.o						\
	system/unix/print.o						\
	system/unix/string.o
