# SPDX-License-Identifier: GPL-2.0

-include lib/toslibc/lib/Makefile
-include lib/toslibc/tool/Makefile
ifndef TOSLINK
$(warning WARNING: Missing toslibc Git submodule; clone with the "--recurse-submodules" option, or do "git submodule update --init --recursive")
endif

include lib/version/Makefile
include lib/tos/Makefile
include lib/ice/Makefile
include lib/internal/Makefile
include lib/m68k/Makefile
include lib/atari/Makefile

include lib/psgplay/Makefile

include lib/example/Makefile

include lib/out/Makefile
include lib/vt/Makefile
include lib/unicode/Makefile
include lib/text/Makefile
