# SPDX-License-Identifier: GPL-2.0

include lib/atari/Makefile
include lib/example/Makefile
include lib/ice/Makefile
include lib/internal/Makefile
include lib/m68k/Makefile
include lib/out/Makefile
include lib/psgplay/Makefile
include lib/text/Makefile
include lib/tos/Makefile
include lib/fujilibc/Makefile
include lib/unicode/Makefile
include lib/version/Makefile
include lib/vt/Makefile
