#!/bin/bash

set -e
set -o pipefail

if [ $# != 2 ]
then
	echo "usage: $0 <input> <output>" >&2
	exit 1
fi

if [ x"$XXD" = x ]
then
	echo "$0"': error: the XXD environment variable for the "xxd" command is undefined' >&2
	exit 1
fi

src="$1"
dst="$2"

echo 'static u8 tos[] = {'	 >"$dst".tmp
"$XXD" -i <"$src"		>>"$dst".tmp
echo '};'			>>"$dst".tmp
mv "$dst".tmp "$dst"
