#!/bin/sh

set -e
set -o pipefail

mod=$([ -z "$(git status -suno)" ] || echo "+")
tag="$(git describe --always --tags)"
ver="$(echo "$tag" | sed 's/^v//')$mod"

if [ $# = 0 ]
then
	echo "$ver"
	exit
fi

[ $# = 1 ]
f="$1"

src=$(echo "#include "'"'"psgplay/version.h"'"'"

const char *psgplay_version(void) { return "'"'"$ver"'"'"; }")

if [ ! -f "$f" ] || ! echo "$src" | cmp --quiet - "$f"
then
	echo "$src" >"$f".tmp
	mv "$f".tmp "$f"
	echo "$f"
else
	:
fi
